--- 
title: "Tee's AD-Webseite"
author: "Joffrey Anthony"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Tee's Wörterbuch

In diesem Template, werde ich dir mein Cheat-Sheet zum Verfassen eines Artikels geben.

## Fachwörter

- Die 3 Komponenten eines Lautsprechers: 
  
  1) Hochtöner
  2) Mitteltöner
  3) Bass // Basstreiber
  
- "Besser heraushören" kann Unterschiedliches bedeuten:

  - Mehr Klarheit
  - Mehr Differenzierung
  - Mehr Intensität
  - Mehr Fülle = erhöhte Musikpräsenz
  - Sensationelle Präzision im Klangbild
  - klangfarbliche Reinheit
  - tonale Neutralität
  - ohne Schleier = grauschleierfrei
  - sehr präzise = hochakkurat
  - Extreme Treue in den Klangfarben
  - Mehr Nuancen im Bass = Konturen im Untergeschoss
  - Harmonierendes Klangspektrum
  - Breiteres Bassspektrum
  - akkurateres Frequenzspektrum = harmonierenderes Frequenzspektrum 
  - Ein noch höheres Mass an Transparenz, Dynamik und Musikalität erlebbar gemacht
  - Bessere Wahrnehmung der Konturen
  
    - <u>Beispiele</u>: 
        - Bläser-Attacken sind strahlender,
        - Perkussionen sind um einiges explosiver,
        - Die Interpreten zeigen noch mehr Emotionen: bei ruhigen Passagen wirkt alles noch zarter und romantischer.
        - Bei dramatischen Momenten wird - umgekehrt - alles schwarzer und angespannter.
        - Die Klangszene wächst dadurch deutlich in Breite und Tiefe
        - Die Konturen der Musiker gewinnen an Schärfe.
        - Verfärbungen und Resonanzen werden beseitigt.
        - Unter solchen Bedingungen wird die Anlage 
        fähig sein, sowohl extremste Finesse, wie auch - umgekehrt - enormen Druck widerzugeben.
        - Ebenfalls sofort spürbar ist die erhöhte Musikpräsenz: die Töne wirken weder trocken noch abgemagert.
        - Was als Erstes auffällt, ist die Grösse der Klangszene. Diese zeichnet sich als aussergewöhnlich breit und tief aus.
        - Ebenfalls sofort spürbar ist die erhöhte Musikpräsenz: die Töne wirken weder trocken noch abgemagert. Die Instrumente klingen prächtig und mit hoher Sättigung. Die Sängerinnen zeichnen sich durch kräftige Stimmen aus.
        - Die Gesamtperformance strotz förmlich vor Autorität und Selbstsicherheit. Dadruch erscheinen Kontrabasse tiefer & voller, Violinen organischer und Becken haben mehr Gewicht.
        - Die Zuhörer werden buchstäblich von der Wirkung der Musik angesteckt, was den Spassfaktor am Musiksystem verdoppelt. 
        - Der Bass wird definierter, greifbarer, dunkler und gewinnt an Tiefe und Gewicht. Auch ist alles nuancenreicher. So ist es möglich, die - oftmals - eintönigen Melodielinien in dem Frequenzbereich besser zu folgen. 
        - Der Test mit dem Verstärker A-75 der Marke zeigte ähnliche Ergebnisse: mehr Wucht, präzisere Musik-Konturen, sowie mehr Halt & Kraft sind typisch für diese neue Accuphase-Generation. Wenn wir diese neue Entwicklung auf nur eine Eigenschaft reduzieren müssten, dann wäre es der deutlich ausgeprägtere Klangkontrast.
        - Auch im Mitteltonbereich hört sich der Intensitätsgewinn sofort. Frauenstimmen werden dadurch noch realistischer. Die Atmung, die Artikulation, die ganze körperliche Anstrengung, um dem Publikum die Emotion einer Interpretation zu vermitteln, kommt klar und deutlich zum Vorschein, mit viel Natürlichkeit.
        - Die Scala Utopia EVO verfügt über eine extreme Homogenität: abgrundtiefe Bässe, organische Mitten und seidige Höhen charakterisieren den Lautsprecher.
        - Die Box zeichnet sich durch messerscharfe Präzision aus, ohne dabei der Musikalität zu schaden.
        - Auch bei der Stimmen-Wiedergabe zeigt sich die Focal Viva Utopia EVO faszinierend. Voll, packend und mit einer sehr neutral abgestimmten Tonalität serviert Ihnen dieser Lautsprecher eine Salve feinster Musikdetails.
        - Verantwortlich für die hochakkurate Transparenz und Klarheit sind die extrem tiefen Verzerrungswerte (0.00025%), sowie der kaum messbare Rauschabstandswert (-130 dB). Der Musikfluss wird dadurch messerscharf und das Gefühl, buchstäblich in die Musik einzutauchen, wird vermittelt.
        - Die beiden Medium-Treiber - ausgestattet mit letzter "TMD-Technologie" und fantastisch leistungsfähigen Beryllium-Hochtönern - 
zeichnen zusammen Klangbilder mit einer Akribie von einem anderen Stern.
        - Im Stimmenbereich fällt der organische Mitteltöner auf. So können die Phrasierungen und kontrastierende Tonhöhen bei der Aussprache natürlicher und selbstverständlicher wahrgenommen werden, was der Musik-Botschaft einen klaren Authentizitäts-Gewinn verschafft.
        
## Marken-Artikel

- <u>Marken Beschreibung</u>:

  - Gründungsjahr: Anektdote, weshalb der Gründer die Marke gründete?
  - Produktkategorien der Marke
  - Preise der Marke
  - Lebenszyklus einer Marke: was waren die Kernereignisse im Lebenszyklus. Dies hilft dem Leser, den aktuellen Erfolg [& Status] der Marke besser zu verstehen. 
  - spezifischer Klang der Geräte?
  - weitere kritische Erfolgsfaktoren (besondere Technologien, Marketing etc.)?
  - Alleinstellungsmerkmal?
  
## Bindewörter

- Aus technischer // XY Sicht ...
- Ausserdem
- Dadurch = Damit = Aufgrund dessen = daher = so
- Entsprechend
- Genauso wie ...
- Hier 
- Hierbei 
- In 1976...
- Jedoch
- Nach
- Natürlich
- Neben ...
- Nebenbei
- Später ...
- Um es bildlich auszudrücken ...
- Wie ...
- Zu diesem Zeitpunkt ...
- Zugleich

## Synonyme

- als Erstes = zuerst
- anpacken = gehandhabt
- Ansatz = Lösung
- Audiophile = Musikbegeisterte = Klangfanatiker = High-Ender
- Auszeichnung = Preis = Dekorierung = Anerkennung = Medaille
- beschreiben = charakterisieren = ausdrücken = darstellen
- billig = erschwinlich
- clever = raffiniert = geschickte
- Design = Ästhetik
- Eigenschaft = Merkmal = Charakteristiken = Besonderheiten
- Eindruck = Empfindung = Wahrnehmung = Anschein = Gefühl 
- Entwicklung = Konzeption
- ermöglichen = bewerkstelligen
- Feinabstimmung = Justage
- Frequenzbereich = Frequenzspektrum
- Fingerspitzengefühl = Gespür
- förmlich = buchstäblich = geradezu = praktisch
- garantieren = sicherstellen
- Geburt = Aufkommen
- gelungen = stimmig
- Gerät = Gerätschaft = Apparatur = Anlage 
- gleichzeitig = simultan = zugleich
- Gründer = Eigner
- Hörraum = Wohnfläche = Interieur 
- in der Lage sein = imstande sein = fähig sein
- Integration = Einbau
- komisch = kurios
- kompakt = schlicht = schlichte Ästhetik = zierlich = klein, aber fein
- konstant = gleichbleibend
- kontrastieren = gegenüberstellen = abgrenzen = sich abheben von ... = abweichen = herausstechen
- Magazin = Revue = Zeitschrift = Heft 
- Musikstück = Musikpassage
- offensichtlich = naheliegend = nachvollziehbar = evident = einleuchtend
- Perfektionist = Klangfanatiker = Musikbegeisterte
- Preisinflation in der Hifi = Audiophile Wahnsinn
- positiv auffallen = brillieren
- präzise = akribisch
- Reputation = Renommee
- rigoros = minuziös = perfektionistisch
- sehr präzise = hochakkurat
- sehr klein = bescheiden
- seit Kurzem = neurdings
- ständig = stets = fortlaufend = andauernd
- Unternehmen = Marke = _Name der Unternehmung_ = Betrieb = Konzern = Manufaktur = Firma = Nobel-Audioschmiede = Start-Up
- übertreffen = niederringen = durchsetzen = überbieten = übertrumpfen
- umsetzen = implementieren
- Ziel = Vorhaben

## Ausdrücke

- Der Devialet ist erste Sahne = mit dem Devialet lässt sich bereits exquisite Klang-Sphären erreichen
- ein Flair für den Lautsprecherbau besitzen = ein Gespür für den Lautsprecherbau besitzen
- vereinfacht ausgedrückt = salopp ausgedrückt
- mehr Transparenz = höhere Transparenz = Transparenzgewinn


## Grammatik

Hier eine Auflistung aller grammatikalischen Punkte, bei denen ich schon Probleme hatte:

### "Alles" oder "alles"?

- **Alles** schreibt man **immer** klein.
  - <u>**Beispiel**</u>: Es braucht gar nicht unbedingt viel Platz, aber alles ist an Bord.
  - <u>Ausnahme</u>: der Ausdruck *mein ein und Alles*. Dort wird "alles" grossgeschrieben.
  
### "Als Erstes" oder "Als erstes"?

- Wenn man mit *als Erstes* das Wort **zuerst** meint, dann schreibt man es gross.
  - <u>**Beispiel**</u>: Als Erstes solltest du dich bei ihm entschuldigen.

- Wenn man es als Adjektiv verwendet, dann schreibt man *als erstes* es klein.
  - <u>**Beispiel**</u>: Als erstes Beispiel solltest du die Geschichte über deinen Bruder erzählen.
  
### Weder ... noch ... mit Komma oder ohne?

- Es braucht grundsätzlich nur ein Komma, wenn es ein **verschachtelter Nebensatz** zwischen dem "weder" und "noch" hat. Ansonsten sind keine Kommas nötig.
  - <u>**Beispiel**</u>: Ich brauche weder neue Bleistifte, mit denen ich ohnehin nicht schreibe, noch bestelle ich neue Kugelschreiber, weil ich sie noch vorrätig habe.
  - <u>**Fazit**</u>: *In 90% der Zeit keine Kommas*!


## Von Tee häufig verwendet Wörter

- Charge = Belastung = Ladung
- Densität = Druck = Intensität
- extasieren = entzücken
- kann der Accuphase ... = ist in der Lage = fähig sein = imstande
- majestuös = prächtig
- magnifizieren = über sich hinauswachsen = sublimieren = verfeinern = veredeln = verbessern
- klanglich besser als ... = klanglich einen höherwertigeren Gesamteindruck
- wir sind verliebt // wir sind eingeliebt = wir sind entzückt 
- Temperaturdrift (bei CH Precision Exact Bias) = Temperaturabweichungen
- Valeur sûre = eine sichere Investition 

## Sonstige nützliche Adjektive

- **adäquat** = angemessen, entsprechend
- affektiert = gekünstelt, geziert
- agil = beweglich, wendig
- **akribisch** = höchst sorgfältig, äusserst gründlich
- **antagonistisch** = gegensätzlich, widerstreitend
- apathisch = teilnahmslos, **abgestumpft**, **gleichgültig**
- **arbiträr** = beliebig, willkürlich
- argusäugig = scharf beobachtend, wachsam
- arkan = geheim, nicht zugänglich
- arriviert = **angesehen**, **etabliert**, **sich profilieren**
- **banal** = nichts Besonderes, alltäglich, gewöhnlich
- bigott = frömmelnd, scheinheilig
- **brachial** = handgreiflich, mit roher Körperkraft
- **designiert** = für etwas (z.B. eine Aufgabe, ein Amt) vorgesehen
- desolat = trostlos, traurig, miserabel
- **diabolisch** = teuflisch
- **diametral** = entgegengesetzt, gegensätzlich
- **differenziert** = fein abgestuft, **nuanciert**
- **diffizil** = schwierig, kompliziert
- diffus = unklar, ungeordnet, **verschwommen**
- disparat = **ungleichartig**, **nicht zueinanderpassend**
- disponibel = sofort verfügbar, frei
- distinguiert = betont vornehm
- **divergent** = entgegengesetzt, auseinanderstreben,
- dolorös = schmerzhaft
- durabel = dauerhaft, **haltbar**, **stabil**
- **effektiv** = wirksam
- **effizient** = viel Leistung in Relation zum Aufwand
- elanvoll = mit Schwung und Begeisterung
- eloquent = redegewandt, wortreich
- eminent = sehr, ausserordentlich, äusserst
- **explizit** = ausdrücklich, deutlich
- **formidabel** = beeindruckend, frappierend
- fulminant = ausgezeichnet, toll, grossartig
- generös = grosszügig,
- **gravierend** = schwerwiegend
- ikonisch = bildhaft, anschaulich
- illuster = berühmt, namhaft, Bewunderung hervorrufen
- **illustrativ** = veranschaulichen, erläuternd
- impertinent = ungehörig, frech, unverschämt
- **inadäquat** = unangemessen, unpassend
- **inakkurat** = unsorgfältig, ungenau
- infernalisch = höllisch, teuflisch, unerträglich
- informell = lässig, locker, leger
- ingeniös = **erfinderisch**, **schöpferisch**
- insistent = beharrlich, hartnäckig
- insolent = anmassend, unverschämt, frech
- **irrelevant** = unerheblich, ohne Bedeutung
- **kausal** = ursächlich
- kongenial = einem Genie ebenbürtig 
- **konsistent** = stabil, **beständig** 
- konsterniert = bestürzt, fassungslos
- **konträr** = entegegengesetzt, gegensächlich
- **kurios** = **merkwürdig**, skurril
- lapidar = kurz und knapp, pointiert
- **legitim** = gesetzlich anerkannt, rechtmässig
- loyal = vertragstreu, redlich
- lukrativ = einträglich, gewinnbringend
- luziferisch = teuflisch, bösartig
- **maliziös** = **boshaft**
- **marginal** = geringfügig, unwichtig, vernachlässigbar
- **medioker** = mittelmässig
- mokant = spöttisch
- morbid = **kränklich**, angekränkelt, brüchig
- **nebulös** = **verschwommen**, unklar
- neuralgisch = besonders empfindlich, anfällig für Störungen
- obligatorisch = bindend, vorgeschrieben, verbindlich
- **obsolet** = überflüssig, nicht mehr üblich
- obstinat = starrsinnig, unbelehrbar
- opportun = gelegen kommend, von Vorteil
- **opulent** = **üppig**, verschwenderisch
- ostentativ = **betont**, provozierend, zur Schau stellend
- pekuniär = geldlich, finanziell
- penibel = kleinlich
- perfide = verschlagen, hinterhältig, gemein
- perniziös = unheilvoll, verderblich, bösartig
- pittoresk = malerisch
- **pointiert** = gezielt, **scharf zugespitzt**
- **prädestiniert** = in hohem Masse geeignet
- **prägnant** = etwas in knapper Form genau treffend
- präsent = anwesend, gegenwärtig
- prätentiös = sich wichtig machen, Eindruck machen wollend
- prekär = schwierig, heikel, misslich
- preziös = gekünstelt, **unnatürlich**
- **prononciert** = eindeutig, entschieden, betont
- prosaisch = nüchtern, sachlich, trocken
- relevant = **bedeutsam**, wichtig
- **renommiert** = angesehen, geschätzt
- respektabel = Respekt verdienend, achtbar
- sakrosankt = **unantastbar**
- satanisch = **abgrundtief böse**, boshaft, teuflisch
- sibyllinisch = rätselhaft, orakelhaft
- **skurril** = seltsam, **befremdlich**
- sublim = erhaben, verfeinert
- **subtil** = mit Feingefühl, mit Sorgfalt
- **superb** = ausgezeichnet, vorzüglich, aussergewöhnlich
- tolerabel = annehmbar, **erträglich**
- tradiert = überliefert, traditionell
- triumphant = triumphierend, siegreich, erfolgreich
- **trivial** = durchschnittlich, alltäglich, gewöhnlich, (einfach?)
- unprätentiös = bescheiden
- vakant = im Augenblick frei, nicht besetzt, offen
- vehement = heftig, ungestüm
- versiert = Bescheid wissen, geschickt